project:
  type: website
  output-dir: docs

website:
  title: "UCSB-Library-OSSSI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - services.qmd
      - instruction.qmd
      - engagement.qmd
    background: primary
    foreground: light       # for contrast

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-location: left
    toc-expand: true
