project:
  type: website
  output-dir: docs

website:
  title: "UCSB-Library-OSSSI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - services.qmd
      - instruction.qmd
      - engagement.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



