project:
  type: website
  output-dir: docs

website:
  title: "UCSB Library Open Science Inventory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quarto-pages/services.qmd
        text: Services & Programs
      - href: quarto-pages/instruction.qmd
        text: Instruction & Consultation
      - href: quarto-pages/engagement.qmd
        text: Engagement & Community
#     right:
#      - icon: github
#        href: https://github.com/xiuqili-xl/UCSB-Library-OSSSI
    background: primary
    foreground: light       # for contrast

format:
  html:
    theme: yeti
    css: styles.css
    page-layout: full
    toc: true
    toc-location: right
    toc-expand: true