project:
  type: website
  output-dir: docs

website:
  title: "UCSB Library Open Science Inventory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - services.qmd
      - instruction.qmd
      - engagement.qmd
    background: primary
    foreground: light       # for contrast

format:
  html:
    theme: yeti
    css: styles.css
    page-layout: full
    toc: true
    toc-location: right
    toc-expand: true

copyright: "Copyright 2026, UCSB Library"
license: "Licensed under CC BY-NC 4.0"